version: "3.9"
services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  frontend:
    image: nginx:alpine
    container_name: frontend-app
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
